* Fechando um Portal
** Começamos a sessão subindo para a sala do altar no [[id:902a71ab-
A "estática" vindo do portal é muito presente, nos sentimos até um 
Perguntada sobre ele, Ariadne reitera que é uma ferida planar.
Ela começa o ritual necessário para fechar a ferida, e percebemos o portal reagindo e aparentemente resistindo esses esforços.

Ouvimos mais barulhos vindo de dentro dele e vemos tentáculos.
Sai a parte de baixo de um polvo do portal, mas em vez de uma boca ele tem um olho, assim como nas pontas de seus tentáculos.
Apesar disso, Ariadne continua concentradíssima em seu ritual.

Conseguimos ocupar o monstro enquanto Ariadne se concentra, inclusive com um grito consigo afastá-lo da Ariadne e o encurralamos em uma pequana câmara lateral.
Nisso, ele foca o olho de um tentáculo em Chonk, que parece agarrado por um força invisível e levantado no ar.
Outro tentáculo foca em Ariadne, mas ela continua em sua concentração, mesmo após seu nariz também começar a sangrar.
Um terceiro foca em Dare, que leva as mãos à cabeça com uma expressão de dor, começando a sangrar do nariz e ouvidos.
Ele consegue fugir para fora da visão do polvo, que vira para Lucky.
Os olhos dela ficam vidrados e ela não se move por um tempo.

Dare se aproxima de novo e tenta atacar a criatura, mas parece estar se desequilibrando e errando os golpes.
Frustrado e machucado, Dare larga sua espada, sacando um escudo e um martelo.
Em sua fúria, acerta o monstro com toda sua força e arranca um dos tentáculos.

Ariadne consegue terminar de fechar o portal, mas está visivelmente abatida.
O monstro continua nos ameaçando, mas Dare logo consegue amassar o restante do corpo dele.

Interpretação dramática: o guerreiro lutando com uma espada amaldiçoada que herdou de seu amado pai, teve que destruir sua herança para ser vitorioso.
** Observações Edificantes

Ariadne avisa que esse portal é apenas o primeiro, que mais surgirão.
Era sabido que o primeiro surgiria nesse [[id:902a71ab-818e-4796-bf7a-ed07529da91d][templo]], mas a partir de agora podem aparecer em qualquer lugar.

Ela nos leva através de um portal. Emergimos um um local com céu noturno, mas as estrelas parecem verdes. Há um caminho de pedra com cores estranhas. À nossa frente uma torre enorme, cujo topo não conseguimos ver. Atrás de nós há um penhasco, notamos que a ilha flutua. Ariadne diz "Bem vindos a Turmion". É um lugar no limiar entre planos.

Todas as pessoas que vemos aqui vestem trajes brancos e um medalhão dourado, com expressões serenas. Vemos tieflings e criaturas semelhantes, porém aparentemente elementais/naturais (e.g., meio planta, meio vulcânica...).

Lucky puxa papo com a criatura de madeira, que se chama [[brieles]] . Perguntada sobre o que eles são, diz que são "Observadores". Ri e diz a Ariadne que claramente não falamos com o cara que precisamos falar.
De vez em quando vemos criaturas mundanas, mas são claramente a minoria.

Na porta da torre tem uma Tiefling azul estranhamente animada: [[id:1f5af35a-d5a4-4c29-8396-60a3b66c213e][Chandri]]. Ela está frustrada que o lugar é muito chato e feliz que é uma batedora, então pode sair de lá.

Entrando na torre, subimos por uma escada espiral subindo por muitos andares antes de vermos o domo da torre, ao longe. Ariadne nos leva ao centro da torre, que é um elevador mágico, e diz que [[id:ced5372e-f547-43ca-bd8f-d9125e203a4a][Eulália]] vai nos explicar tudo. Subimos até o topo. Olhando pelas janelas, se vê o ambiente meio alienígena, com ainda mais ilhas flutuando. Entramos em uma sala que parece ser um semi-plano, com um céu estrelado dentro dela mesmo. Sentada num "trono" no fundo da sala está Eulália, parece feita de escuridão mas com detalhes dourados na pele.

Ela diz que é Galtir do dragão dourado, e ao contrário dos outros Galtir ela é a primeira e será a última.
Nos dá uma aula de cosmologia, usando a analogia de uma árvore.
Ela está toda em perigo pois a segunda dimensão está se conectando com a nossa, e deveria ser só acessível como transição após a morte.
Esse desequilíbrio teria sido criado após o fim do período de graça em que todos viviam em harmonia.
Após o fim da harmonia, o desequilíbrio começou e apenas cresceu.
O desequilíbrio tem a ver com a disputa por poder e riquezas, a criação de inimizade.

O templo onde passamos seria onde o dragão dividiu a jóia da criação em quatro e deu aos seus filhos.
Como observadores, aparentemente eles não podem interferir diretamente.

Aparentemente para resolver o problema de fato é necessário reunir as quatro jóias da criação que estão com os galtires.
Galtires acessam um pedaço da consciência dos respectivos deuses.

Dare pergunta sobre como isso pode funcionar, e de fato vai ser difícil pois os Galtir podem não querer abrir mão.
Como são joias de grande poder, só a ameaça de possuí-las é um fator importante nos conflitos entre esses países.

Toda vez que fechamos um portal, um "medalhão do destino" coleta uma certa energia que pode nos ajudar.
Podemos acessar isso com "anéis filhos" desse medalhão.

A névoa mágica que esconde esse lugar causa o esquecimento quando uma criatura sai de lá. Nós recebemos uma runa que nos protege disso, mas ficamos proibidos magicamente, fisicamente incapazes de passer informações sobre Turmion e Eulália. Mas podemos falar sobre o problema do mundo se desfazendo.

Nos retiramos para descansar e pensar se queremos aceitar essa missão.
Vamos para a janta e é de fato tão chato quanto [[id:1f5af35a-d5a4-4c29-8396-60a3b66c213e][Chandri]] tinha falado, nem a comida tem muito gosto.

Nos reunimos para tomar decisões. Confabulamos sobre a ordem dos lugares, os irmãos me contam parte do seu passado (gangue de rinha de autômatos em [[id:29b53953-6a17-42ac-83c5-eb9ef460c572][Alabaster]], foi atacada e após a fuga os irmãos estavam sendo perseguidos). Decidimos tentar focar em [[id:e0cf71c7-786c-4154-8b87-e57ceeb6f7b7][Gaelyra]] primeiro. Depois disso vamos dormir.

No dia seguinte, Ariadne nos leva de volta a Eulália. Quando eu falo na cabeça dos irmãos, ela também ouve e responde. Consultando ela sobre nossos planos, ela concorda que Idrarus e Khreven são os casos mais difíceis. Com Ida talvez seja possível até negociar. Depois, descemos para outro andar da torre onde recebemos as tatuagens. [[Brieles]] é o nosso tatuador. Também nos dá os anéis do destino, inclusive um extra para Chonk. Ariadne pega anéis extra caso outros aventureiros se juntem a nós.

O anel nos dá a magia "Speak with Allies".

Todos passam para nível 4.